### ISSUE TITLE
Question about download speed

### ISSUE THREAD

**Issue by shimon128** [negrutiu/nsis-nscurl#6]
I started the download at a speed of 20 MB/s and the time that was listed as remaining was 20 minutes and slowly it increased until I reached the situation in the picture (and it continued to increase).
![image](https://user-images.githubusercontent.com/70193333/224544550-0e9f4fdf-5416-4862-988f-b625f58b995e.png)
Is there anything I can write that can make it better?

**Comment by shimon128** [comment]
Something strange that I have no explanation for.
I turned it on once and right at the start the download speed and download time was just bad, I closed it and turned it on again and then the speed is great and the time is just fast.
And towards the end I suddenly get this again, what is it?
![image](https://user-images.githubusercontent.com/70193333/224632463-87da6100-bdf6-4956-9d29-3bcc06082cb4.png)

**Comment by negrutiu** [comment]
There are two issues here:
- The ridiculous "remaining time" displayed there. I'll have a look and fix it in the next release
- The drop in the download speed. `NScurl` itself has very little to do with the download logic. It all sits in the underlying `libcurl`. If the speed drops it's usually because of external factors (server overloaded, VPN connection slow downs, etc.)

**Have you tried to download the same file with `curl` itself?**
Try `curl -L -o localfile.bin <URL>` and see if you notice the same drop in speed. I suggest you use `curl/7.85.0` which my latest release is based on.

**Are you willing to share the URL with this issue?**
If I could reproduce it maybe I could come up with a fix.

Thanks for reporting the issue.

**Comment by negrutiu** [comment]
I think I may have found the problem.

What you've described might happen if your network connectivity were lost for more than 60s during the transfer.
There was a bug where the plugin is unable to properly detect connection drops and the download keeps going although no data is being transfered any longer. In such case the speed would keep going down until those weird ETAs are reported.

I've fixed this issue in the latest release.
Feel free to give it a try and see what happens.

**Comment by shimon128** [comment]
Thank you very much, I will check it out.
As for the URL, do you still need it?
If so, I can check if I can send it to you, but only privately.

**Comment by shimon128** [comment]
![image](https://user-images.githubusercontent.com/70193333/226167078-f11e0cf9-bbb0-4dc2-8320-b52cc7af5897.png)
I'm confused.
Why does it show the infinity sign when it's really about to end?
"display infinity sign when the ETA is very large (over one month)"
And it finished after two minutes.

**Comment by negrutiu** [comment]
Something is weird over there...
The infinity sign is displayed because it looks like the total size is unknown, therefore I can't compute the remaining time.
In your screenshot I noticed "12.7 GB / \<blank\> GB" suggesting that for whatever reason the remote length becomes unknown during the transfer.
I haven't encountered this behavior yet...

Few more questions:
- Did your connection dropped&restored during the transfer?
- Apart from the infinity sign, was everything else ok?
- If the issue still persists, the URL would be very helpful. If you choose to share it feel free to use my personal email marius.negrutiu(at)protonmail(dot)com. I promise I won'd disclose it ;-)

**Comment by shimon128** [comment]
the <blank> is because of the Hebrew, the order is not presented well.
the 11.3 should be in the <blank> place

**Comment by shimon128** [comment]
Did your connection dropped&restored during the transfer? No
Apart from the infinity sign, was everything else ok? Yes

**Comment by shimon128** [comment]
I sent you an email

**Comment by negrutiu** [comment]
Thanks Shimon,
With your link I was able to find the bug immediately.
It was an ETA calculation error. I've ran into integer overflows when multiplying high 64-bit numbers
Fixed the issue in the latest release. Please check it out.
...and thanks for all your feedback! 👍🏻

**Comment by shimon128** [comment]
Indeed, better.
Thank you very much.
I sent you two videos in an email, one shows a good download speed and the other starts well and then drops drastically, both on the same computer with the same internet speed and the same connection.
If you have any idea what can try I would love to hear it.
And again, thank you very much for everything.

**Comment by negrutiu** [comment]
Watched the video... hard to say why that happens.
The speed keeps dropping, but bear in mind that that's the **average speed** being displayed.
In your case I think that the "real" speed drops to zero:
- To confirm that you could display `@XFERSIZE_B@` and see if you have moments with 0 bytes transferred
- You could also run tests with `curl` itself and see if you encounter the same issue

I suspect you have occasional connection drops/lags and then the transfer resumes.
This is likely to happen if your're in a VPN and/or unstable wifi networks...

**Comment by shimon128** [comment]
I am connected with a cable.
I tried the same download through Chrome and there it was very stable with 57 MB/s

**Comment by shimon128** [comment]
I sent you another video by email.
with what you suggested before curl through CMD and at the same time with yours.
![image](https://user-images.githubusercontent.com/70193333/226889255-51665c99-779c-44b0-822a-dcb723c12f9e.png)
This is the result of downloading through CMD

**Comment by negrutiu** [comment]
I've ran some more tests and I've made some changes that hopefully improve things a bit.

Brief changelog:
- Modified `@SPEED@` keyword to return the current speed instead of the average speed. For example:
```nsis
NScurl::http GET "${LINK}" "${FILE}" /STRING TEXT "[@PERCENT@%] @TIMEELAPSED@ / @TIMEREMAINING@, @XFERSIZE@ / @FILESIZE@, Average @AVGSPEED@, Speed @SPEED@" /INSIST /TIMEOUT 1m /USERAGENT "curl/@CURLVERSION@" /TITLEWND $HWNDPARENT /END
```
- Updated `libcurl` and its dependencies to their latest versions
- Activated some speed optimizations in the compiler

***
One thing that I've noticed is that `curl.exe` itself performs differenly based on the SSL engine that it's using (NOTE: curl supports [multiple SSL libraries](https://curl.se/docs/ssl-compared.html)).
With your URL, `schannel` (aka WinSSL) engine performs much better than `openssl` engine.
On your machine you've probably used the default `curl.exe` that comes with Windows, which is built on top of `schannel`.
My `NScurl` extension is built with the `openssl` library...
That's probably why the default `curl.exe` performs better than your installer, at least for some URLs/webservers.
Why is that happening?... I have no clue. That's a good question for the `curl` authors.

My `NScurl` extension is optimized for backward compatibility not necessarily for speed. It needs to run on all Windows versions including the ancient Windows NT4, Windows 2000, etc.
For me `openssl` is the only way to go, I can't switch to `schannel` unfortunately.

***
Please give the latest version a try, maybe you'll notice some improvements...

(Thanks again for the URL and all the videos that you've sent. They were really helpful during the "investigation")

**Comment by shimon128** [comment]
Hi,
It took me some time, I checked and it is indeed better and shows the current download speed and is relatively close to the Windows curl.
Thank you so much for everything and this amazing project.

**Comment by negrutiu** [comment]
Sounds great. I'll close this bug for now
If you still encounter speed issues feel free to open a new one
